<?xml version="1.0"?>
<package>
  <name>scarab_mpc</name>
  <version>0.0.0</version>
  <description>ROS MPC controller package for Scarab differential-drive robots.</description>
  <maintainer email="grasp@localhost.local">grasp</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>geometry_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>scarab_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>

  <run_depend>geometry_msgs</run_depend>
  <run_depend>gazebo_ros</run_depend>
  <run_depend>joint_state_publisher</run_depend>
  <run_depend>kinematic_sim</run_depend>
  <run_depend>nav_msgs</run_depend>
  <run_depend>robot_state_publisher</run_depend>
  <run_depend>rospy</run_depend>
  <run_depend>rviz</run_depend>
  <run_depend>scarab</run_depend>
  <run_depend>scarab_description</run_depend>
  <run_depend>scarab_gazebo</run_depend>
  <run_depend>scarab_msgs</run_depend>
  <run_depend>std_msgs</run_depend>
  <run_depend>tf</run_depend>
  <run_depend>tf2_ros</run_depend>
  <run_depend>visualization_msgs</run_depend>
  <run_depend>xacro</run_depend>
</package>
